<?php
function db_connect()
{
    $servername = 'localhost';
    $username = 'root';
    $password = '';
    $database = 'sbtbsphp';

    $conn = mysqli_connect($servername, $username, $password, $database);
    return $conn;
}

$conn = db_connect();

// Define your queries
$queries = [
    'Total bookings per day' => "SELECT DATE(booking_created) AS date, COUNT(*) AS total_bookings FROM bookings GROUP BY DATE(booking_created)",
    'Most popular routes based on the number of bookings' => "SELECT route_id, COUNT(*) AS total_bookings FROM bookings GROUP BY route_id ORDER BY total_bookings DESC",
    'Revenue generated per route' => "SELECT route_id, SUM(booked_amount) AS total_revenue FROM bookings GROUP BY route_id",
    'Average booking amount per day/week/month' => "SELECT DATE(booking_created) AS date, AVG(booked_amount) AS average_amount FROM bookings GROUP BY DATE(booking_created)",
    'Number of bookings per bus' => "SELECT r.bus_no, COUNT(*) AS total_bookings FROM bookings b JOIN routes r ON b.route_id = r.route_id GROUP BY r.bus_no",
    'Routes assigned to each bus' => "SELECT bus_no, GROUP_CONCAT(route_id) AS routes FROM routes GROUP BY bus_no",
    'Buses that are currently unassigned' => "SELECT bus_no FROM buses WHERE bus_assigned = 0",
    'Number of bookings made by each customer' => "SELECT customer_id, COUNT(*) AS total_bookings FROM bookings GROUP BY customer_id",
    'Most frequent routes taken by each customer' => "SELECT customer_id, route_id, COUNT(*) AS total_bookings FROM bookings GROUP BY customer_id, route_id ORDER BY total_bookings DESC",
    'Total revenue generated by each customer' => "SELECT customer_id, SUM(booked_amount) AS total_revenue FROM bookings GROUP BY customer_id",
    'Number of bookings for each route' => "SELECT route_id, COUNT(*) AS total_bookings FROM bookings GROUP BY route_id",
    'Revenue generated from each route' => "SELECT route_id, SUM(booked_amount) AS total_revenue FROM bookings GROUP BY route_id",
    'Buses assigned to each route' => "SELECT route_id, bus_no FROM routes",
    // Add other queries here...
];

echo "<html><head>";
echo "<style>
table {
    border-collapse: collapse;
    width: 100%;
}
th, td {
    border: 1px solid #ddd;
    padding: 8px;
}
tr:nth-child(even) {
    background-color: #f2f2f2;
}
th {
    background-color: #4CAF50;
    color: white;
}
</style>";
echo "</head><body>";

foreach ($queries as $title => $query) {
    $result = mysqli_query($conn, $query);

    echo "<h2>$title</h2>";
    echo "<table>";
    // Fetch the first row to get the column names
    $row = mysqli_fetch_assoc($result);
    echo "<tr>";
    foreach ($row as $col => $val) {
        echo "<th>$col</th>";
    }
    echo "</tr>";
    // Output the first row
    echo "<tr>";
    foreach ($row as $val) {
        echo "<td>$val</td>";
    }
    echo "</tr>";
    // Output the rest of the rows
    while ($row = mysqli_fetch_assoc($result)) {
        echo "<tr>";
        foreach ($row as $val) {
            echo "<td>$val</td>";
        }
        echo "</tr>";
    }
    echo "</table>";
}

mysqli_close($conn);

echo "</body></html>";
?>

